CREATE TABLE IF NOT EXISTS USERS
(
    TABLE_INDEX  int auto_increment primary key,
    USER_NAME varchar(50)  not null,
    PASSWORD varchar(100) not null,
    HOBBY varchar(50),
    ROLE varchar(50) not null
);

CREATE TABLE IF NOT EXISTS USER_REFRESH_TOKEN
(
    TABLE_INDEX  INT AUTO_INCREMENT PRIMARY KEY,
    USER_NAME    VARCHAR(50) NOT NULL,
    USER_AGENT   VARCHAR(500) NOT NULL,
    REFRESH_TOKEN VARCHAR(200),
    REG_DATE     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY (USER_NAME, USER_AGENT)
);