spring:
  application:
    name: jwt-server
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: false

  datasource:
    url: jdbc:h2:mem:chameleon;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3000

jwt:
  token:
    secret-key: hello-jwt
    valid-time: 60000 # ms (1분)
    refresh-valid-time: 259200000 # ms (3일)


resilience4j:
  circuitbreaker:
    configs:
      redis:
        slidingWindowSize: 1
        failureRateThreshold: 100
        waitDurationInOpenState: 1m
        slow-call-duration-threshold: 3s
        slow-call-rate-threshold: 100
        permitted-number-of-calls-in-half-open-state: 5
    instances:
      redis:
        base-config: redis